name: Deploy to surge

on:
  push:
    branches:
      - time-garden

jobs:
       build:                           
           runs-on: ubuntu-latest 
           name: Deploying to surge 
           steps:
           - uses: actions/checkout@v2
           
           - name: Install Node.js
             uses: actions/setup-node@v2-beta
             with:
               node-version: 14
               registry-url: https://registry.npmjs.org

           - name: Make hardhat envfile
             uses: SpicyPizza/create-envfile@v1
             with:
               envkey_REACT_APP_NETWORK: ${{ secrets.REACT_APP_NETWORK }}
               envkey_REACT_APP_PROVIDER: ${{ secrets.REACT_APP_PROVIDER }}
               envkey_MNEMONIC: ${{ secrets.MNEMONIC }}

               file_name: packages/hardhat/.env

           - name: Make react envfile
             uses: SpicyPizza/create-envfile@v1
             with:
               envkey_REACT_APP_NETWORK: ${{ secrets.REACT_APP_NETWORK }}
               envkey_REACT_APP_PROVIDER: ${{ secrets.REACT_APP_PROVIDER }}
               envkey_MNEMONIC: ${{ secrets.MNEMONIC }}

               file_name: packages/react-app/.env                

           - name: Install dependencies
             run: yarn install --frozen-lockfile

           - name: Deploy contract
             run: yarn deploy

           - name: Build React App                              
             run: yarn build 

           - name: Install Surge
             run: npm install --global surge  

           - name: Run surge
             run: surge --project ./build --domain time-garden.surge.sh --token ${{ secrets.SURGE_TOKEN }}